[build]
  publish = "exampleSite/public"
  command = '''hugo -s exampleSite --config "exampleSite/config.toml"'''

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"


[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"

# [context.production.environment]
#   HUGO_VERSION = "0.51"

# [context.deploy-preview.environment]
#   HUGO_VERSION = "0.51"

# [context.branch-deploy.environment]
#   HUGO_VERSION = "0.51"
  
